# Generated by Django 5.2.5 on 2025-09-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_skills_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.CharField(default='IN', max_length=50),
        ),
    ]
