# Generated by Django 5.2.5 on 2025-09-04 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_brand_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.brand'),
        ),
    ]
